export const presetFacets = [
  {
    title: 'Case',
    field: 'case_id',
    full: 'cases.case_id',
    doc_type: 'cases',
    type: 'id',
  },
  {
    title: 'Case ID',
    field: 'submitter_id',
    full: 'cases.submitter_id',
    doc_type: 'cases',
    type: 'id',
    placeholder: 'eg. TCGA-DD*, *DD*, TCGA-DD-AAVP',
  },
  {
    title: 'Primary Site',
    field: 'primary_site',
    full: 'cases.primary_site',
    doc_type: 'cases',
    type: 'keyword',
  },
  {
    title: 'Program',
    field: 'project.program.name',
    full: 'cases.project.program.name',
    doc_type: 'cases',
    type: 'keyword',
  },
  {
    title: 'Project',
    field: 'project.project_id',
    full: 'cases.project.project_id',
    doc_type: 'cases',
    type: 'terms',
  },
  {
    title: 'Disease Type',
    field: 'disease_type',
    full: 'cases.disease_type',
    doc_type: 'cases',
    type: 'keyword',
  },
  {
    title: 'Experimental Strategy',
    field: 'summary.experimental_strategies.experimental_strategy',
    full: 'cases.summary.experimental_strategies.experimental_strategy',
    doc_type: 'cases',
    type: 'keyword',
  },
  {
    title: 'Sample Type',
    field: 'samples.sample_type',
    full: 'cases.samples.sample_type',
    doc_type: 'cases',
    type: 'keyword',
  },

  {
    title: 'Available Variation Data',
    field: 'available_variation_data',
    full: 'cases.available_variation_data',
    doc_type: 'cases',
    type: 'keyword',
  },
];
const excludedRegex = [
  /updated_datetime$/,
  /created_datetime$/,
  /_id$/,
  /state$/,
];
interface IClinicalFacetProps {
  title: string;
  field: string;
  full: string;
  excluded: RegExp[];
}
export const clinicalFacets: IClinicalFacetProps[] = [
  {
    title: 'Demographic',
    field: 'demographic',
    full: 'cases.demographic',
    excluded: [...excludedRegex],
  },
  {
    title: 'Diagnoses',
    field: 'diagnoses',
    full: 'cases.diagnoses',
    excluded: [...excludedRegex, /^cases.diagnoses.treatments/],
  },
  {
    title: 'Treatments',
    field: 'treatments',
    full: 'cases.diagnoses.treatments',
    excluded: [...excludedRegex],
  },
  {
    title: 'Exposures',
    field: 'exposures',
    full: 'cases.exposures',
    excluded: [...excludedRegex],
  },
];

const clinicalFacetSortingDictionary = {
  demographic: [
    'gender',
    'race',
    'ethnicity',
    'vital_status',
    'cause_of_death',
    'premature_at_birth',
    'days_to_death',
    'days_to_birth',
    'year_of_birth',
    'year_of_death',
  ],
  diagnoses: [
    'age_at_diagnosis',
    'year_of_diagnosis',
    'ajcc_clinical_stage',
    'ajcc_clinical_t',
    'ajcc_clinical_n',
    'ajcc_clinical_m',
    'ajcc_pathologic_stage',
    'ajcc_pathologic_t',
    'ajcc_pathologic_n',
    'ajcc_pathologic_m',
    'ajcc_staging_system_edition',
    'classification_of_tumor',
    'first_symptom_prior_to_diagnosis',
    'method_of_diagnosis',
    'primary_diagnosis',
    'prior_malignancy',
    'prior_treatment',
    'synchronous_malignancy',
    'anaplasia_present',
    'anaplasia_present_type',
    'ann_arbor_clinical_stage',
    'ann_arbor_pathologic_stage',
    'ann_arbor_extranodal_involvement',
    'ann_arbor_b_symptoms',
    'burkitt_lymphoma_clinical_variant',
    'child_pugh_classification',
    'cog_liver_stage',
    'cog_neuroblastoma_risk_group',
    'cog_renal_stage',
    'cog_rhabdomyosarcoma_risk_group',
    'enneking_msts_grade',
    'enneking_msts_metastasis',
    'enneking_msts_stage',
    'enneking_msts_tumor_site',
    'esophageal_columnar_dysplasia_degree',
    'esophageal_columnar_metaplasia_present',
    'figo_stage',
    'inpc_grade',
    'inpc_histologic_group',
    'inrg_stage',
    'inss_stage',
    'irs_group',
    'irs_stage',
    'ishak_fibrosis_score',
    'iss_stage',
    'lymph_nodes_positive',
    'lymph_nodes_tested',
    'medulloblastoma_molecular_classification',
    'metastasis_at_diagnosis',
    'metastasis_at_diagnosis_site',
    'micropapillary_features',
    'mitosis_karyorrhexis_index',
    'morphology',
    'tumor_grade',
    'tumor_regression_grade',
    'wilms_tumor_histologic_subtype',
    'tissue_or_organ_of_origin',
    'site_of_resection_or_biopsy',
    'circumferential_resection_margin',
    'laterality',
    'supratentorial_localization',
    'gastric_esophageal_junction_involvement',
    'lymphatic_invasion_present',
    'perineural_invasion_present',
    'peripancreatic_lymph_nodes_positive',
    'tumor_confined_to_organ_of_origin',
    'tumor_focality',
    'tumor_largest_dimension_diameter',
    'vascular_invasion_present',
    'vascular_invasion_type',
    'best_overall_response',
    'progression_or_recurrence',
    'residual_disease',
  ],
  'diagnoses.treatments': [
    'days_to_treatment_start',
    'days_to_treatment_end',
    'therapeutic_agents',
    'initial_disease_status',
    'treatment_anatomic_site',
    'treatment_effect',
    'treatment_intent_type',
    'treatment_or_therapy',
    'treatment_outcome',
    'treatment_type',
  ],
  exposures: [
    'alcohol_history',
    'alcohol_intensity',
    'asbestos_exposure',
    'radon_exposure',
    'tobacco_smoking_status',
  ],
}

export const customSorting = (field: string = ''): object | number => {
  const fieldPath: string[] = field.split('.');
  const ordersArray = clinicalFacetSortingDictionary[fieldPath.slice(0, -1).join('.')];
  const position = ordersArray && ordersArray.indexOf(fieldPath.slice(-1)[0]);
  return position > -1 ? - ordersArray.length + position : 0;
};
