include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/deployments/salt-service.yaml

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [ portal, awgportal ]

stages:
  - test
  - build

variables:
  npm_config_registry: https://nexus.osdc.io/repository/npm-all/
  DEPLOY_SERVICE_TAG: ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DEPLOY_SERVICE_TAG: ${CI_COMMIT_BRANCH}-${CI_COMMIT_TAG}
    - when: always

test:
  allow_failure: true
  stage: test
  image: docker.osdc.io/node:13
  before_script:
    - npm install
  script:
    - npm run lint
    - npm test

build:portal-ui:
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  script:
    - docker build --build-arg "NPM_REGISTRY=https://nexus.osdc.io/repository/npm-all/" -t $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA} -f portal.Dockerfile .
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}

build:awg-portal:
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  script:
    - docker build --build-arg "NPM_REGISTRY=https://nexus.osdc.io/repository/npm-all/" -t $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA} -f awgportal.Dockerfile .
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}

build:portal-ui:latest:
  only:
    - master
  needs:
    - build:portal-ui
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  script:
    - docker pull $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}
    - docker tag $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA} $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:latest
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:latest

build:awg-portal:latest:
  only:
    - master
  needs:
    - build:awg-portal
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  script:
    - docker pull $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}
    - docker tag $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA} $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:latest
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:latest

build:portal-ui:tag:
  only:
    - tags
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  script:
    - docker pull $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}
    - docker tag $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA} $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:${CI_COMMIT_TAG}
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:${CI_COMMIT_TAG}

build:awg-portal:tag:
  only:
    - tags
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  script:
    - docker pull $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}
    - docker tag $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA} $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:${CI_COMMIT_TAG}
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/awgportal:${CI_COMMIT_TAG}
