include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/deployments/salt-service.yaml

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [ portal, awgportal ]

stages:
  - test
  - build
  - release
  - deploy

variables:
  npm_config_registry: https://nexus.osdc.io/repository/npm-all/
  DEPLOY_SERVICE_TAG: ${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      variables:
        DEPLOY_SERVICE_TAG: ${CI_COMMIT_BRANCH}-${CI_COMMIT_TAG}
    - when: always

test:
  allow_failure: true
  stage: test
  image: docker.osdc.io/node:13
  script:
    - npm ci
    - npm run lint
    - npm test

build:
  stage: build
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  parallel:
    matrix:
      - IMAGE_NAME: portal-ui
        DOCKER_FILE: portal.Dockerfile
      - IMAGE_NAME: portal-ui-awg
        DOCKER_FILE: awgportal.Dockerfile
  script:
    - |
      docker build \
        --build-arg "NPM_REGISTRY=https://nexus.osdc.io/repository/npm-all/" \
        -t $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA} \
        -t $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:$CI_COMMIT_SHA \
        -f $DOCKER_FILE . \
        --progress=plain
    - docker push -a $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME

release:latest:
  only:
    - master
  stage: release
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  parallel:
    matrix:
      - IMAGE_NAME: [portal-ui, portal-ui-awg]
  script:
    - docker pull $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:latest
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:latest

release:tag:
  only:
    - tags
  stage: release
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  parallel:
    matrix:
      - IMAGE_NAME: [portal-ui, portal-ui-awg]
  script:
    - docker pull $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:$CI_COMMIT_SHA
    - docker tag $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:$CI_COMMIT_SHA $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:${CI_COMMIT_TAG}
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/$IMAGE_NAME:${CI_COMMIT_TAG}
