version: "3.3"
services:
  app:
    image: jenkins-agent:node
    environment:
      CI: 'true'
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      HTTPS_PROXY: http://cloud-proxy:3128
      HTTP_PROXY: http://cloud-proxy:3128
      NO_PROXY: localhost
    volumes:
    - .:/home/jenkins
    - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    command: bash -c "npm install && npm run lint && npm test"