apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "portal-ui.fullname" . }}-nginx-config
    labels:
        {{- include "portal-ui.labels" . | nindent 6 }}
data:
{{ (tpl (.Files.Glob "files/portal.conf").AsConfig .) | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "portal-ui.proxy.fullname" . }}-nginx-config
    labels:
        {{- include "portal-ui.labels" . | nindent 6 }}
data:
{{ (tpl (.Files.Glob "files/proxy.conf").AsConfig .)| indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "portal-ui.proxy.fullname" . }}-nginx-proxy-params
    labels:
        {{- include "portal-ui.labels" . | nindent 6 }}
data:
{{ (tpl (.Files.Glob "files/proxy_params").AsConfig .)| indent 4 }}
