---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-istio-destinationrule
  labels:
    app.kubernetes.io/name: {{ include "k8s-service.name" . }}
    helm.sh/chart: {{ include "k8s-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  host: portal.{{.Release.Namespace}}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
