/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CartPage_viewer.graphql
 * @generated SignedSource<<83c2118fa12a5d066ffe7c657746614a>>
 * @flow
 * @nogrep
 */

"use strict";

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type CartPage_viewer = {
  summary?: ?CartPage_viewer_summary;
  repository?: ?CartPage_viewer_repository;
};

export type CartPage_viewer_summary_aggregations_project__project_id_buckets = {
  case_count?: ?number;
  doc_count?: ?number;
  file_size?: ?number;
  key?: ?string;
};

export type CartPage_viewer_summary_aggregations_project__project_id = {
  buckets?: ?Array<?CartPage_viewer_summary_aggregations_project__project_id_buckets>;
};

export type CartPage_viewer_summary_aggregations_fs = {
  value?: ?number;
};

export type CartPage_viewer_summary_aggregations = {
  project__project_id?: ?CartPage_viewer_summary_aggregations_project__project_id;
  fs?: ?CartPage_viewer_summary_aggregations_fs;
};

export type CartPage_viewer_summary = {
  aggregations?: ?CartPage_viewer_summary_aggregations;
};

export type CartPage_viewer_repository_files = {
  hits?: ?any;
};

export type CartPage_viewer_repository = {
  files?: ?CartPage_viewer_repository_files;
};
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [
    {
      kind: "RootArgument",
      name: "filters",
      type: "FiltersArgument"
    },
    {
      kind: "RootArgument",
      name: "files_size",
      type: "Int"
    },
    {
      kind: "RootArgument",
      name: "files_offset",
      type: "Int"
    },
    {
      kind: "RootArgument",
      name: "files_sort",
      type: "[Sort]"
    }
  ],
  kind: "Fragment",
  metadata: null,
  name: "CartPage_viewer",
  selections: [
    {
      kind: "LinkedField",
      alias: "summary",
      args: null,
      concreteType: "CartSummary",
      name: "cart_summary",
      plural: false,
      selections: [
        {
          kind: "LinkedField",
          alias: null,
          args: [
            {
              kind: "Variable",
              name: "filters",
              variableName: "filters",
              type: "FiltersArgument"
            }
          ],
          concreteType: "CartSummaryAggs",
          name: "aggregations",
          plural: false,
          selections: [
            {
              kind: "LinkedField",
              alias: null,
              args: null,
              concreteType: "SummaryAggregations",
              name: "project__project_id",
              plural: false,
              selections: [
                {
                  kind: "LinkedField",
                  alias: null,
                  args: null,
                  concreteType: "CartSummaryBucket",
                  name: "buckets",
                  plural: true,
                  selections: [
                    {
                      kind: "ScalarField",
                      alias: null,
                      args: null,
                      name: "case_count",
                      storageKey: null
                    },
                    {
                      kind: "ScalarField",
                      alias: null,
                      args: null,
                      name: "doc_count",
                      storageKey: null
                    },
                    {
                      kind: "ScalarField",
                      alias: null,
                      args: null,
                      name: "file_size",
                      storageKey: null
                    },
                    {
                      kind: "ScalarField",
                      alias: null,
                      args: null,
                      name: "key",
                      storageKey: null
                    }
                  ],
                  storageKey: null
                }
              ],
              storageKey: null
            },
            {
              kind: "LinkedField",
              alias: null,
              args: null,
              concreteType: "FileSize",
              name: "fs",
              plural: false,
              selections: [
                {
                  kind: "ScalarField",
                  alias: null,
                  args: null,
                  name: "value",
                  storageKey: null
                }
              ],
              storageKey: null
            }
          ],
          storageKey: null
        }
      ],
      storageKey: null
    },
    {
      kind: "LinkedField",
      alias: null,
      args: null,
      concreteType: "Repository",
      name: "repository",
      plural: false,
      selections: [
        {
          kind: "LinkedField",
          alias: null,
          args: null,
          concreteType: "Files",
          name: "files",
          plural: false,
          selections: [
            {
              kind: "LinkedField",
              alias: null,
              args: [
                {
                  kind: "Variable",
                  name: "filters",
                  variableName: "filters",
                  type: "FiltersArgument"
                },
                {
                  kind: "Variable",
                  name: "first",
                  variableName: "files_size",
                  type: "Int"
                },
                {
                  kind: "Variable",
                  name: "offset",
                  variableName: "files_offset",
                  type: "Int"
                },
                {
                  kind: "Variable",
                  name: "sort",
                  variableName: "files_sort",
                  type: "[Sort]"
                }
              ],
              concreteType: "FileConnection",
              name: "hits",
              plural: false,
              selections: [
                {
                  kind: "FragmentSpread",
                  name: "FileTable_hits",
                  args: null
                }
              ],
              storageKey: null
            }
          ],
          storageKey: null
        }
      ],
      storageKey: null
    }
  ],
  type: "Root"
};

module.exports = fragment;
