/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule ProjectTable_projects.graphql
 * @generated SignedSource<<ddf27073b94680c762b0db730e54698e>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

"use strict";

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type ProjectTable_projects = {|
  +total: number;
  +edges: ?$ReadOnlyArray<?{|
    +node: ?{|
      +id: string;
      +project_id: ?string;
      +disease_type: ?$ReadOnlyArray<?string>;
      +program: ?{|
        +name: ?string;
      |};
      +primary_site: ?$ReadOnlyArray<?string>;
      +summary: ?{|
        +case_count: ?number;
        +data_categories: ?$ReadOnlyArray<?{|
          +case_count: ?number;
          +data_category: ?string;
        |}>;
        +file_count: ?number;
      |};
    |};
  |}>;
|};
*/

const fragment /*: ConcreteFragment*/ = {
  argumentDefinitions: [],
  kind: "Fragment",
  metadata: null,
  name: "ProjectTable_projects",
  selections: [
    {
      kind: "ScalarField",
      alias: null,
      args: null,
      name: "total",
      storageKey: null
    },
    {
      kind: "LinkedField",
      alias: null,
      args: null,
      concreteType: "ProjectEdge",
      name: "edges",
      plural: true,
      selections: [
        {
          kind: "LinkedField",
          alias: null,
          args: null,
          concreteType: "Project",
          name: "node",
          plural: false,
          selections: [
            {
              kind: "ScalarField",
              alias: null,
              args: null,
              name: "id",
              storageKey: null
            },
            {
              kind: "ScalarField",
              alias: null,
              args: null,
              name: "project_id",
              storageKey: null
            },
            {
              kind: "ScalarField",
              alias: null,
              args: null,
              name: "disease_type",
              storageKey: null
            },
            {
              kind: "LinkedField",
              alias: null,
              args: null,
              concreteType: "Program",
              name: "program",
              plural: false,
              selections: [
                {
                  kind: "ScalarField",
                  alias: null,
                  args: null,
                  name: "name",
                  storageKey: null
                }
              ],
              storageKey: null
            },
            {
              kind: "ScalarField",
              alias: null,
              args: null,
              name: "primary_site",
              storageKey: null
            },
            {
              kind: "LinkedField",
              alias: null,
              args: null,
              concreteType: "Summary",
              name: "summary",
              plural: false,
              selections: [
                {
                  kind: "ScalarField",
                  alias: null,
                  args: null,
                  name: "case_count",
                  storageKey: null
                },
                {
                  kind: "LinkedField",
                  alias: null,
                  args: null,
                  concreteType: "DataCategories",
                  name: "data_categories",
                  plural: true,
                  selections: [
                    {
                      kind: "ScalarField",
                      alias: null,
                      args: null,
                      name: "case_count",
                      storageKey: null
                    },
                    {
                      kind: "ScalarField",
                      alias: null,
                      args: null,
                      name: "data_category",
                      storageKey: null
                    }
                  ],
                  storageKey: null
                },
                {
                  kind: "ScalarField",
                  alias: null,
                  args: null,
                  name: "file_count",
                  storageKey: null
                }
              ],
              storageKey: null
            }
          ],
          storageKey: null
        }
      ],
      storageKey: null
    }
  ],
  type: "ProjectConnection"
};

module.exports = fragment;
