/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule CohortComparison_relayQuery.graphql
 * @generated SignedSource<<8acb4bd557e49935ee8fa537429b103d>>
 * @relayHash bda0879596e1519b2230f9bbaf9d4fae
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query CohortComparison_relayQuery(
  $filter1: FiltersArgument
  $filter2: FiltersArgument
  $facets: [String]!
) {
  viewer {
    repository {
      result1: cases {
        hits(filters: $filter1) {
          total
        }
        facets(filters: $filter1, facets: $facets)
      }
      result2: cases {
        hits(filters: $filter2) {
          total
        }
        facets(filters: $filter2, facets: $facets)
      }
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "filter1",
        "type": "FiltersArgument",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "filter2",
        "type": "FiltersArgument",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "facets",
        "type": "[String]!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "CohortComparison_relayQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Root",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Repository",
            "name": "repository",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": "result1",
                "args": null,
                "concreteType": "RepositoryCases",
                "name": "cases",
                "plural": false,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter1",
                        "type": "FiltersArgument"
                      }
                    ],
                    "concreteType": "CaseConnection",
                    "name": "hits",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "total",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "facets",
                        "variableName": "facets",
                        "type": "[String]!"
                      },
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter1",
                        "type": "FiltersArgument"
                      }
                    ],
                    "name": "facets",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": "result2",
                "args": null,
                "concreteType": "RepositoryCases",
                "name": "cases",
                "plural": false,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter2",
                        "type": "FiltersArgument"
                      }
                    ],
                    "concreteType": "CaseConnection",
                    "name": "hits",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "total",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "facets",
                        "variableName": "facets",
                        "type": "[String]!"
                      },
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter2",
                        "type": "FiltersArgument"
                      }
                    ],
                    "name": "facets",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Root"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "CohortComparison_relayQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "filter1",
        "type": "FiltersArgument",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "filter2",
        "type": "FiltersArgument",
        "defaultValue": null
      },
      {
        "kind": "LocalArgument",
        "name": "facets",
        "type": "[String]!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "CohortComparison_relayQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Root",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "Repository",
            "name": "repository",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": "result1",
                "args": null,
                "concreteType": "RepositoryCases",
                "name": "cases",
                "plural": false,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter1",
                        "type": "FiltersArgument"
                      }
                    ],
                    "concreteType": "CaseConnection",
                    "name": "hits",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "total",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "facets",
                        "variableName": "facets",
                        "type": "[String]!"
                      },
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter1",
                        "type": "FiltersArgument"
                      }
                    ],
                    "name": "facets",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": "result2",
                "args": null,
                "concreteType": "RepositoryCases",
                "name": "cases",
                "plural": false,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter2",
                        "type": "FiltersArgument"
                      }
                    ],
                    "concreteType": "CaseConnection",
                    "name": "hits",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "total",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  },
                  {
                    "kind": "ScalarField",
                    "alias": null,
                    "args": [
                      {
                        "kind": "Variable",
                        "name": "facets",
                        "variableName": "facets",
                        "type": "[String]!"
                      },
                      {
                        "kind": "Variable",
                        "name": "filters",
                        "variableName": "filter2",
                        "type": "FiltersArgument"
                      }
                    ],
                    "name": "facets",
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query CohortComparison_relayQuery(\n  $filter1: FiltersArgument\n  $filter2: FiltersArgument\n  $facets: [String]!\n) {\n  viewer {\n    repository {\n      result1: cases {\n        hits(filters: $filter1) {\n          total\n        }\n        facets(filters: $filter1, facets: $facets)\n      }\n      result2: cases {\n        hits(filters: $filter2) {\n          total\n        }\n        facets(filters: $filter2, facets: $facets)\n      }\n    }\n  }\n}\n"
};

module.exports = batch;
