export default {
  'demographic.ethnicity': {
    active_calculation: 'number',
    active_chart: 'histogram',
    active_survival: 'overall',
    bins: {},
    continuousBinType: 'default',
    plotTypes: 'categorical',
    scrollToCard: false,
    type: 'Demographic',
  },

  'demographic.gender': {
    active_calculation: 'number',
    active_chart: 'histogram',
    active_survival: 'overall',
    bins: {},
    continuousBinType: 'default',
    plotTypes: 'categorical',
    scrollToCard: false,
    type: 'Demographic',
  },

  'demographic.race': {
    active_calculation: 'number',
    active_chart: 'histogram',
    active_survival: 'overall',
    bins: [],
    continuousBinType: 'default',
    plotTypes: 'categorical',
    scrollToCard: false,
    type: 'Demographic',
  },
  'diagnoses.age_at_diagnosis': {
    active_calculation: 'number',
    active_chart: 'histogram',
    active_survival: 'overall',
    bins: {},
    continuousBinType: 'default',
    plotTypes: 'continuous',
    scrollToCard: false,
    type: 'Diagnosis',
  },
  'diagnoses.primary_diagnosis': {
    active_calculation: 'number',
    active_chart: 'histogram',
    active_survival: 'overall',
    bins: {},
    continuousBinType: 'default',
    plotTypes: 'categorical',
    scrollToCard: false,
    type: 'Diagnosis',
  },
};
