module ngApp.participants {
  "use strict";

  import IParticipantsService = ngApp.participants.services.IParticipantsService;
  import IParticipant = ngApp.participants.models.IParticipant;

  /* @ngInject */
  function participantsConfig($stateProvider: ng.ui.IStateProvider) {
    $stateProvider.state("participant", {
      url: "/participants/:participantId",
      controller: "ParticipantController as pc",
      templateUrl: "participant/templates/participant.html",
      resolve: {
        participant: ($stateParams: ng.ui.IStateParamsService, ParticipantsService: IParticipantsService): ng.IPromise<IParticipant> => {
          return ParticipantsService.getParticipant($stateParams["participantId"], {
            fields: [
              "participant_id",
              "submitter_id",
              "clinical.vital_status",
              "clinical.ethnicity",
              "clinical.gender",
              "clinical.race",
              "clinical.icd_10",
              "files.file_id",
              "files.data_format",
              "files.data_type",
              "files.data_subtype",
              "project.name",
              "project.project_id",
              "project.primary_site",
              "project.program.name",
              "project.disease_type",
              "summary.experimental_strategies.experimental_strategy",
              "summary.experimental_strategies.file_count",
              "summary.data_types.file_count",
              "summary.data_types.data_type",
              "samples.sample_type_id",
              "samples.pathology_report_uuid",
              "samples.portions.creation_datetime",
              "samples.portions.portion_number",
              "samples.portions.weight",
              "samples.portions.analytes.well_number",
              "samples.portions.analytes.analyte_type",
              "samples.portions.analytes.submitter_id",
              "samples.portions.analytes.analyte_id",
              "samples.portions.analytes.amount",
              "samples.portions.analytes.aliquots.center.code",
              "samples.portions.analytes.aliquots.center.name",
              "samples.portions.analytes.aliquots.center.short_name",
              "samples.portions.analytes.aliquots.center.namespace",
              "samples.portions.analytes.aliquots.center.center_id",
              "samples.portions.analytes.aliquots.center.center_type",
              "samples.portions.analytes.aliquots.submitter_id",
              "samples.portions.analytes.aliquots.amount",
              "samples.portions.analytes.aliquots.aliquot_id",
              "samples.portions.analytes.aliquots.concentration",
              "samples.portions.analytes.aliquots.source_center",
              "samples.portions.analytes.aliquots.annotations.category",
              "samples.portions.analytes.aliquots.annotations.status",
              "samples.portions.analytes.aliquots.annotations.classification",
              "samples.portions.analytes.aliquots.annotations.creator",
              "samples.portions.analytes.aliquots.annotations.created_datetime",
              "samples.portions.analytes.aliquots.annotations.notes",
              "samples.portions.analytes.aliquots.annotations.submitter_id",
              "samples.portions.analytes.aliquots.annotations.item_type",
              "samples.portions.analytes.aliquots.annotations.participant_id",
              "samples.portions.analytes.aliquots.annotations.item_id",
              "samples.portions.analytes.aliquots.annotations.annotation_id",
              "samples.portions.analytes.a260_a280_ratio",
              "samples.portions.analytes.concentration",
              "samples.portions.analytes.spectrophotometer_method",
              "samples.portions.analytes.analyte_type_id",
              "samples.portions.analytes.annotations.category",
              "samples.portions.analytes.annotations.status",
              "samples.portions.analytes.annotations.classification",
              "samples.portions.analytes.annotations.creator",
              "samples.portions.analytes.annotations.created_datetime",
              "samples.portions.analytes.annotations.notes",
              "samples.portions.analytes.annotations.submitter_id",
              "samples.portions.analytes.annotations.item_type",
              "samples.portions.analytes.annotations.participant_id",
              "samples.portions.analytes.annotations.item_id",
              "samples.portions.analytes.annotations.annotation_id",
              "samples.portions.submitter_id",
              "samples.portions.slides.percent_tumor_nuclei",
              "samples.portions.slides.percent_monocyte_infiltration",
              "samples.portions.slides.percent_normal_cells",
              "samples.portions.slides.annotations.category",
              "samples.portions.slides.annotations.status",
              "samples.portions.slides.annotations.classification",
              "samples.portions.slides.annotations.creator",
              "samples.portions.slides.annotations.created_datetime",
              "samples.portions.slides.annotations.notes",
              "samples.portions.slides.annotations.submitter_id",
              "samples.portions.slides.annotations.item_type",
              "samples.portions.slides.annotations.participant_id",
              "samples.portions.slides.annotations.item_id",
              "samples.portions.slides.annotations.annotation_id",
              "samples.portions.slides.submitter_id",
              "samples.portions.slides.percent_eosinophil_infiltration",
              "samples.portions.slides.percent_lymphocyte_infiltration",
              "samples.portions.slides.percent_stromal_cells",
              "samples.portions.slides.section_location",
              "samples.portions.slides.slide_id",
              "samples.portions.slides.percent_necrosis",
              "samples.portions.slides.percent_granulocyte_infiltration",
              "samples.portions.slides.percent_inflam_infiltration",
              "samples.portions.slides.percent_neutrophil_infiltration",
              "samples.portions.slides.number_proliferating_cells",
              "samples.portions.slides.percent_tumor_cells",
              "samples.portions.portion_id",
              "samples.portions.is_ffpe",
              "samples.portions.annotations.category",
              "samples.portions.annotations.status",
              "samples.portions.annotations.classification",
              "samples.portions.annotations.creator",
              "samples.portions.annotations.created_datetime",
              "samples.portions.annotations.notes",
              "samples.portions.annotations.submitter_id",
              "samples.portions.annotations.item_type",
              "samples.portions.annotations.participant_id",
              "samples.portions.annotations.item_id",
              "samples.portions.annotations.annotation_id",
              "samples.portions.center.code",
              "samples.portions.center.name",
              "samples.portions.center.short_name",
              "samples.portions.center.namespace",
              "samples.portions.center.center_id",
              "samples.portions.center.center_type",
              "samples.time_between_clamping_and_freezing",
              "samples.time_between_excision_and_freezing",
              "samples.shortest_dimension",
              "samples.oct_embedded",
              "samples.tumor_code_id",
              "samples.tumor_code",
              "samples.sample_type",
              "samples.submitter_id",
              "samples.days_to_collection",
              "samples.intermediate_dimension",
              "samples.days_to_sample_procurement",
              "samples.sample_id",
              "samples.initial_weight",
              "samples.freezing_method",
              "samples.current_weight",
              "samples.annotations.category",
              "samples.annotations.status",
              "samples.annotations.classification",
              "samples.annotations.creator",
              "samples.annotations.created_datetime",
              "samples.annotations.notes",
              "samples.annotations.submitter_id",
              "samples.annotations.item_type",
              "samples.annotations.participant_id",
              "samples.annotations.item_id",
              "samples.annotations.annotation_id",
              "samples.longest_dimension",
              "samples.is_ffpe",
              "annotations.annotation_id"
           ]
          });
        }
      }
    });
  }

  angular
      .module("ngApp.participants", [
        "participants.controller",
        "ui.router.state"
      ])
      .config(participantsConfig);
}
