// LIBS DEFINITION
/// <reference path="libs/jquery.d.ts"/>
/// <reference path="libs/angular.d.ts"/>
/// <reference path="libs/angular-ui-router.d.ts"/>
/// <reference path="libs/lodash.d.ts"/>
/// <reference path="libs/restangular.d.ts"/>
/// <reference path="libs/moment.d.ts"/>
/// <reference path="libs/d3.d.ts"/>
/// <reference path="libs/ngprogress-lite.d.ts"/>
/// <reference path="libs/angular-notify.d.ts"/>
/// <reference path="libs/angular-cookies.d.ts"/>

// APP TYPES
/// <reference path="../scripts/404/module"/>
/// <reference path="../scripts/annotations/module"/>
/// <reference path="../scripts/cart/module"/>
/// <reference path="../scripts/components/module"/>
/// <reference path="../scripts/core/module"/>
/// <reference path="../scripts/files/module"/>
/// <reference path="../scripts/home/module"/>
/// <reference path="../scripts/participant/module"/>
/// <reference path="../scripts/projects/module"/>
/// <reference path="../scripts/query/module"/>
/// <reference path="../scripts/reports/module"/>
/// <reference path="../scripts/search/module"/>